'use client';
import { FormEvent, useEffect, useState } from 'react';
import { siteContent as c } from './siteContent';
const nav=[['Home','home'],['About','about'],['Skills','skills'],['Experience','experience'],['Projects','projects'],['Contact','contact']];
function Heading({n,label,title}:{n:string,label:string,title:string}){return <><p className="kicker">{n} / {label}</p><h2>{title}</h2></>}
export default function Home(){const[light,setLight]=useState(false);useEffect(()=>{document.documentElement.dataset.theme=light?'light':'dark'},[light]);function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);location.href=`mailto:${c.profile.email}?subject=${encodeURIComponent(String(d.get('subject')))}&body=${encodeURIComponent(`Hi Zexu,\n\n${d.get('message')}\n\n— ${d.get('name')}`)}`}
return <><a className="skip" href="#main">Skip to content</a><header className="topbar"><a className="brand" href="#home"><span>ZC</span><b>Zexu Chen<small>Data Analyst</small></b></a><nav aria-label="Main">{nav.map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}</nav><button className="theme" onClick={()=>setLight(!light)} aria-label="Switch colour theme">{light?'☀':'☾'}</button></header><main id="main">
<section id="home" className="hero"><div className="hero-copy"><p className="status"><i/> {c.profile.availability} · {c.profile.location}</p><h1 className="script-name">Zexu Chen</h1><p className="eyebrow">{c.profile.headline}</p><p className="lede">{c.profile.intro}</p><div className="actions"><a className="primary" href="#projects">See what I’ve built <b>→</b></a><a className="secondary" href={c.profile.linkedin} target="_blank" rel="noreferrer">in&nbsp; LinkedIn</a></div><dl className="metrics"><div><dt>Years in analytics</dt><dd>7+</dd></div><div><dt>Analysis runtime cut</dt><dd>99%</dd></div><div><dt>Product line supported</dt><dd>$5M</dd></div></dl></div><aside className="player-card"><div className="stars">★★★★★</div><div className="portrait-placeholder"><img src="/character-cat.png" alt="Illustrated cat wearing glasses and working on a laptop" /></div><div className="card-name">ZEXU <strong>CHEN</strong></div><div className="card-meta"><span>Class · Data Strategist</span><span>Path · Analytics</span></div><div className="stats">{[{name:'SQL',width:95},{name:'Python',width:95},{name:'Analytics',width:95},{name:'Cloud / ETL',width:94},{name:'Visualization',width:95}].map((stat)=><div key={stat.name}><span>{stat.name}</span><i><b style={{width:`${stat.width}%`}}/></i></div>)}</div></aside><a className="scroll" href="#about">⌄</a></section>
<section id="about" className="section"><Heading n="01" label="Profile" title="Nice to meet you"/><div className="about-grid"><div><p className="intro">{c.about[0]}</p>{c.about.slice(1).map(x=><p key={x}>{x}</p>)}<div className="facts"><span>Based in<b>{c.profile.location}</b></span><span>Currently<b>{c.profile.availability}</b></span><span>Education<b>M.S. Operations Research</b></span></div><p className="minor-title">Roles I’m a fit for</p><div className="pills">{c.roles.map(x=><span key={x}>{x}</span>)}</div></div><div><aside className="care"><h3>Things I care about</h3>{c.values.map(x=><p key={x}>▸ {x}</p>)}</aside><aside className="terminal"><span>zexu.py</span><pre>{`class Zexu(DataAnalyst):\n  stack = ["sql", "python", "spark"]\n  north_star = "useful decisions"\n\n  def solve(self, question):\n    return evidence.over_assumption()`}</pre></aside></div></div></section>
<section id="skills" className="section"><Heading n="02" label="Loadout" title="Technical skills"/><p className="section-note">Grouped the way I use them: to move from a question to a reliable, explainable answer.</p><div className="skill-grid">{c.skills.map(s=><article className="skill-card" key={s.title}><h3><i>{s.icon}</i>{s.title}</h3><p>{s.note}</p><div className="pills">{s.items.map(x=><span key={x}>{x}</span>)}</div></article>)}</div></section>
<section id="experience" className="section"><Heading n="03" label="Quest log" title="Work experience"/><div className="timeline">{c.experience.map((job,i)=><article key={job.company+job.period}><div className="time"><span>{job.period}</span>{i===0&&<b>Most recent</b>}</div><div><h3>{job.role}</h3><p className="company">{job.company}<span>{job.place}</span></p><ul>{job.bullets.map(x=><li key={x}>{x}</li>)}</ul></div></article>)}</div><div className="edu"><h3>Education</h3>{c.education.map(x=><article key={x.degree}><div><b>{x.degree}</b><p>{x.school} · {x.place}</p></div><span>{x.year}</span></article>)}</div></section>
<section id="projects" className="section"><Heading n="04" label="Inventory" title="Selected projects"/><p className="section-note">A few examples of analysis that ended in a decision, a product, or a tool someone could use.</p><div className="projects">{c.projects.map(p=><article key={p.title}><header><p>{p.type}</p><h3>{p.title}</h3><div className="pills">{p.tags.map(x=><span key={x}>{x}</span>)}</div></header><div><p className="project-summary">{p.summary}</p><ul>{p.points.map(x=><li key={x}>{x}</li>)}</ul><strong className="project-metric">{p.metric}</strong></div></article>)}</div></section>
<section id="contact" className="section contact"><Heading n="05" label="Say hi" title="Let’s talk"/><p className="intro">Open to data analyst, product analytics, analytics engineering, and data science roles.</p><div className="contact-grid"><div className="contact-links"><a href={`mailto:${c.profile.email}`}><span>✉</span><div><small>Email</small>{c.profile.email}</div><b>→</b></a><a href={c.profile.linkedin} target="_blank" rel="noreferrer"><span>in</span><div><small>LinkedIn</small>linkedin.com/in/zexuchen</div><b>→</b></a><a href={`tel:${c.profile.phone.replace(/[^\d+]/g,'')}`}><span>☎</span><div><small>Phone</small>{c.profile.phone}</div><b>→</b></a></div><form onSubmit={send}><p>This opens your mail app with the message pre-filled.</p><label>Your name<input name="name" required placeholder="Ada Lovelace"/></label><label>Subject<input name="subject" required placeholder="Data role at …"/></label><label>Message<textarea name="message" required placeholder="Hi Zexu, we’re hiring for…"/></label><button className="primary">Send message →</button></form></div></section>
</main><footer>© 2026 Zexu Chen · Built with data, curiosity, and a lot of blue.<a href="#home">↑ Back to top</a></footer></>}
